.globl main
.data
__str__0:
.byte 84
.byte 101
.byte 115
.byte 116
.byte 105
.byte 110
.byte 103
.byte 32
.byte 102
.byte 117
.byte 110
.byte 99
.byte 116
.byte 105
.byte 111
.byte 110
.byte 32
.byte 112
.byte 116
.byte 114
.byte 0
__str__1:
.byte 69
.byte 120
.byte 112
.byte 101
.byte 99
.byte 116
.byte 101
.byte 100
.byte 58
.byte 32
.byte 0
__str__2:
.byte 86
.byte 97
.byte 108
.byte 117
.byte 101
.byte 32
.byte 111
.byte 102
.byte 32
.byte 105
.byte 112
.byte 32
.byte 61
.byte 32
.byte 50
.byte 50
.byte 57
.byte 51
.byte 51
.byte 49
.byte 54
.byte 32
.byte 86
.byte 97
.byte 108
.byte 117
.byte 101
.byte 32
.byte 111
.byte 102
.byte 32
.byte 100
.byte 112
.byte 32
.byte 61
.byte 32
.byte 50
.byte 50
.byte 57
.byte 51
.byte 51
.byte 48
.byte 52
.byte 32
.byte 86
.byte 97
.byte 108
.byte 117
.byte 101
.byte 32
.byte 111
.byte 102
.byte 32
.byte 99
.byte 112
.byte 32
.byte 61
.byte 32
.byte 50
.byte 50
.byte 57
.byte 51
.byte 51
.byte 48
.byte 51
.byte 32
.byte 86
.byte 97
.byte 108
.byte 117
.byte 101
.byte 32
.byte 111
.byte 102
.byte 32
.byte 105
.byte 112
.byte 32
.byte 43
.byte 32
.byte 49
.byte 32
.byte 61
.byte 32
.byte 50
.byte 50
.byte 57
.byte 51
.byte 51
.byte 50
.byte 48
.byte 32
.byte 86
.byte 97
.byte 108
.byte 117
.byte 101
.byte 32
.byte 111
.byte 102
.byte 32
.byte 100
.byte 112
.byte 32
.byte 43
.byte 32
.byte 49
.byte 32
.byte 61
.byte 32
.byte 50
.byte 50
.byte 57
.byte 51
.byte 51
.byte 49
.byte 50
.byte 32
.byte 86
.byte 97
.byte 108
.byte 117
.byte 101
.byte 32
.byte 111
.byte 102
.byte 32
.byte 99
.byte 112
.byte 32
.byte 43
.byte 32
.byte 49
.byte 32
.byte 61
.byte 32
.byte 50
.byte 50
.byte 57
.byte 51
.byte 51
.byte 48
.byte 52
.byte 32
.byte 86
.byte 97
.byte 108
.byte 117
.byte 101
.byte 32
.byte 111
.byte 102
.byte 32
.byte 105
.byte 112
.byte 32
.byte 43
.byte 32
.byte 50
.byte 32
.byte 61
.byte 32
.byte 50
.byte 50
.byte 57
.byte 51
.byte 51
.byte 50
.byte 52
.byte 32
.byte 32
.byte 86
.byte 97
.byte 108
.byte 117
.byte 101
.byte 32
.byte 111
.byte 102
.byte 32
.byte 100
.byte 112
.byte 32
.byte 43
.byte 32
.byte 50
.byte 32
.byte 61
.byte 32
.byte 50
.byte 50
.byte 57
.byte 51
.byte 51
.byte 50
.byte 48
.byte 32
.byte 86
.byte 97
.byte 108
.byte 117
.byte 101
.byte 32
.byte 111
.byte 102
.byte 32
.byte 99
.byte 112
.byte 32
.byte 43
.byte 32
.byte 50
.byte 32
.byte 61
.byte 32
.byte 50
.byte 50
.byte 57
.byte 51
.byte 51
.byte 48
.byte 53
.byte 0
__str__3:
.byte 71
.byte 111
.byte 116
.byte 58
.byte 0
__str__4:
.byte 84
.byte 101
.byte 115
.byte 116
.byte 105
.byte 110
.byte 103
.byte 32
.byte 84
.byte 119
.byte 111
.byte 80
.byte 111
.byte 105
.byte 110
.byte 116
.byte 101
.byte 114
.byte 115
.byte 0
__str__5:
.byte 86
.byte 97
.byte 108
.byte 117
.byte 101
.byte 32
.byte 111
.byte 102
.byte 32
.byte 105
.byte 112
.byte 49
.byte 32
.byte 111
.byte 114
.byte 32
.byte 97
.byte 100
.byte 100
.byte 114
.byte 101
.byte 115
.byte 115
.byte 32
.byte 111
.byte 102
.byte 32
.byte 105
.byte 49
.byte 32
.byte 61
.byte 32
.byte 50
.byte 54
.byte 56
.byte 54
.byte 55
.byte 56
.byte 56
.byte 32
.byte 32
.byte 86
.byte 97
.byte 108
.byte 117
.byte 101
.byte 32
.byte 111
.byte 102
.byte 32
.byte 105
.byte 112
.byte 50
.byte 32
.byte 111
.byte 114
.byte 32
.byte 97
.byte 100
.byte 100
.byte 114
.byte 101
.byte 115
.byte 115
.byte 32
.byte 111
.byte 102
.byte 32
.byte 105
.byte 50
.byte 32
.byte 61
.byte 32
.byte 50
.byte 54
.byte 56
.byte 54
.byte 55
.byte 56
.byte 48
.byte 32
.byte 32
.byte 32
.byte 105
.byte 112
.byte 50
.byte 32
.byte 45
.byte 32
.byte 105
.byte 112
.byte 49
.byte 32
.byte 61
.byte 32
.byte 50
.byte 32
.byte 32
.byte 105
.byte 112
.byte 49
.byte 32
.byte 45
.byte 32
.byte 105
.byte 112
.byte 50
.byte 32
.byte 61
.byte 32
.byte 45
.byte 50
.byte 0
__str__6:
.byte 71
.byte 111
.byte 116
.byte 58
.byte 32
.byte 0
__str__7:
.byte 86
.byte 97
.byte 108
.byte 117
.byte 101
.byte 32
.byte 111
.byte 102
.byte 32
.byte 105
.byte 112
.byte 32
.byte 61
.byte 32
.byte 0
__str__8:
.byte 86
.byte 97
.byte 108
.byte 117
.byte 101
.byte 32
.byte 111
.byte 102
.byte 32
.byte 99
.byte 112
.byte 32
.byte 61
.byte 32
.byte 0
__str__9:
.byte 86
.byte 97
.byte 108
.byte 117
.byte 101
.byte 32
.byte 111
.byte 102
.byte 32
.byte 105
.byte 112
.byte 32
.byte 43
.byte 32
.byte 49
.byte 32
.byte 61
.byte 32
.byte 0
__str__10:
.byte 86
.byte 97
.byte 108
.byte 117
.byte 101
.byte 32
.byte 111
.byte 102
.byte 32
.byte 99
.byte 112
.byte 32
.byte 43
.byte 32
.byte 49
.byte 32
.byte 61
.byte 32
.byte 0
__str__11:
.byte 86
.byte 97
.byte 108
.byte 117
.byte 101
.byte 32
.byte 111
.byte 102
.byte 32
.byte 105
.byte 112
.byte 32
.byte 43
.byte 32
.byte 50
.byte 32
.byte 61
.byte 32
.byte 0
__str__12:
.byte 86
.byte 97
.byte 108
.byte 117
.byte 101
.byte 32
.byte 111
.byte 102
.byte 32
.byte 99
.byte 112
.byte 32
.byte 43
.byte 32
.byte 50
.byte 32
.byte 61
.byte 32
.byte 0
__str__13:
.byte 86
.byte 97
.byte 108
.byte 117
.byte 101
.byte 32
.byte 111
.byte 102
.byte 32
.byte 105
.byte 112
.byte 32
.byte 45
.byte 32
.byte 49
.byte 32
.byte 61
.byte 32
.byte 0
__str__14:
.byte 86
.byte 97
.byte 108
.byte 117
.byte 101
.byte 32
.byte 111
.byte 102
.byte 32
.byte 105
.byte 112
.byte 32
.byte 45
.byte 32
.byte 50
.byte 32
.byte 61
.byte 32
.byte 0
__str__15:
.byte 86
.byte 97
.byte 108
.byte 117
.byte 101
.byte 32
.byte 111
.byte 102
.byte 32
.byte 99
.byte 112
.byte 32
.byte 45
.byte 32
.byte 49
.byte 32
.byte 61
.byte 32
.byte 0
__str__16:
.byte 86
.byte 97
.byte 108
.byte 117
.byte 101
.byte 32
.byte 111
.byte 102
.byte 32
.byte 99
.byte 112
.byte 32
.byte 45
.byte 32
.byte 50
.byte 32
.byte 61
.byte 32
.byte 0
__str__17:
.byte 86
.byte 97
.byte 108
.byte 117
.byte 101
.byte 32
.byte 111
.byte 102
.byte 32
.byte 105
.byte 112
.byte 49
.byte 32
.byte 111
.byte 114
.byte 32
.byte 97
.byte 100
.byte 100
.byte 114
.byte 101
.byte 115
.byte 115
.byte 32
.byte 111
.byte 102
.byte 32
.byte 105
.byte 49
.byte 32
.byte 61
.byte 32
.byte 0
__str__18:
.byte 86
.byte 97
.byte 108
.byte 117
.byte 101
.byte 32
.byte 111
.byte 102
.byte 32
.byte 105
.byte 112
.byte 50
.byte 32
.byte 111
.byte 114
.byte 32
.byte 97
.byte 100
.byte 100
.byte 114
.byte 101
.byte 115
.byte 115
.byte 32
.byte 111
.byte 102
.byte 32
.byte 105
.byte 50
.byte 32
.byte 61
.byte 32
.byte 0
__str__19:
.byte 105
.byte 112
.byte 50
.byte 32
.byte 45
.byte 32
.byte 105
.byte 112
.byte 49
.byte 32
.byte 61
.byte 32
.byte 0
__str__20:
.byte 105
.byte 112
.byte 49
.byte 32
.byte 45
.byte 32
.byte 105
.byte 112
.byte 50
.byte 32
.byte 61
.byte 32
.byte 37
.byte 100
.byte 0
.text
main:
addi sp sp -4
sw fp 0(sp)
mv fp sp
addi sp sp -48
sw ra 0(sp)
sw s1 4(sp)
sw s2 8(sp)
sw s3 12(sp)
sw s4 16(sp)
sw s5 20(sp)
sw s6 24(sp)
sw s7 28(sp)
sw s8 32(sp)
sw s9 36(sp)
sw s10 40(sp)
sw s11 44(sp)
addi sp sp -4
la s1 __str__0
sw s1 0(sp)
jal ra PrintString
mv s1 a0
addi sp sp 4
addi sp sp -4
la s1 __str__1
sw s1 0(sp)
jal ra PrintString
mv s1 a0
addi sp sp 4
jal ra PrintNewline
mv s1 a0
addi sp sp -4
la s1 __str__2
sw s1 0(sp)
jal ra PrintString
mv s1 a0
addi sp sp 4
addi sp sp -4
la s1 __str__3
sw s1 0(sp)
jal ra PrintString
mv s1 a0
addi sp sp 4
jal ra PrintNewline
mv s1 a0
jal ra ptr
mv s1 a0
jal ra PrintNewline
mv s1 a0
addi sp sp -4
la s1 __str__4
sw s1 0(sp)
jal ra PrintString
mv s1 a0
addi sp sp 4
addi sp sp -4
la s1 __str__1
sw s1 0(sp)
jal ra PrintString
mv s1 a0
addi sp sp 4
addi sp sp -4
la s1 __str__5
sw s1 0(sp)
jal ra PrintString
mv s1 a0
addi sp sp 4
jal ra PrintNewline
mv s1 a0
addi sp sp -4
la s1 __str__6
sw s1 0(sp)
jal ra PrintString
mv s1 a0
addi sp sp 4
jal ra TwoPointers
mv s1 a0
li s1 0
mv a0 s1
j _main
_main:
addi sp fp -48
lw s11 44(sp)
lw s10 40(sp)
lw s9 36(sp)
lw s8 32(sp)
lw s7 28(sp)
lw s6 24(sp)
lw s5 20(sp)
lw s4 16(sp)
lw s3 12(sp)
lw s2 8(sp)
lw s1 4(sp)
lw ra 0(sp)
addi sp sp 48
lw fp 0(sp)
addi sp sp 4
mv a1 a0
addi a0 x0 17
ecall
ptr:
addi sp sp -4
sw fp 0(sp)
mv fp sp
addi sp sp -48
sw ra 0(sp)
sw s1 4(sp)
sw s2 8(sp)
sw s3 12(sp)
sw s4 16(sp)
sw s5 20(sp)
sw s6 24(sp)
sw s7 28(sp)
sw s8 32(sp)
sw s9 36(sp)
sw s10 40(sp)
sw s11 44(sp)
addi sp sp -16
li s1 12
sw s1 -52(fp)
addi s1 fp -52
sw s1 -56(fp)
addi s1 x0 97
sb s1 -57(fp)
addi s1 fp -57
sw s1 -64(fp)
addi sp sp -4
la s1 __str__7
sw s1 0(sp)
jal ra PrintString
mv s1 a0
addi sp sp 4
addi sp sp -4
addi s1 fp -56
lw s1 0(s1)
sw s1 0(sp)
jal ra PrintInt
mv s1 a0
addi sp sp 4
jal ra PrintNewline
mv s1 a0
addi sp sp -4
la s1 __str__8
sw s1 0(sp)
jal ra PrintString
mv s1 a0
addi sp sp 4
addi sp sp -4
addi s1 fp -64
lw s1 0(s1)
sw s1 0(sp)
jal ra PrintInt
mv s1 a0
addi sp sp 4
jal ra PrintNewline
mv s1 a0
addi sp sp -4
la s1 __str__9
sw s1 0(sp)
jal ra PrintString
mv s1 a0
addi sp sp 4
addi sp sp -4
addi s1 fp -56
lw s1 0(s1)
addi sp sp -4
sw s1 0(sp)
li s1 1
lw s2 0(sp)
addi sp sp 4
addi t0 x0 4
li t1 1
mul t1 s1 t0
add s2 s2 t1
mv s1 s2
sw s1 0(sp)
jal ra PrintInt
mv s1 a0
addi sp sp 4
jal ra PrintNewline
mv s1 a0
addi sp sp -4
la s1 __str__10
sw s1 0(sp)
jal ra PrintString
mv s1 a0
addi sp sp 4
addi sp sp -4
addi s1 fp -64
lw s1 0(s1)
addi sp sp -4
sw s1 0(sp)
li s1 1
lw s2 0(sp)
addi sp sp 4
addi t0 x0 1
li t1 1
mul t1 s1 t0
add s2 s2 t1
mv s1 s2
sw s1 0(sp)
jal ra PrintInt
mv s1 a0
addi sp sp 4
jal ra PrintNewline
mv s1 a0
addi sp sp -4
la s1 __str__11
sw s1 0(sp)
jal ra PrintString
mv s1 a0
addi sp sp 4
addi sp sp -4
addi s1 fp -56
lw s1 0(s1)
addi sp sp -4
sw s1 0(sp)
li s1 2
lw s2 0(sp)
addi sp sp 4
addi t0 x0 4
li t1 1
mul t1 s1 t0
add s2 s2 t1
mv s1 s2
sw s1 0(sp)
jal ra PrintInt
mv s1 a0
addi sp sp 4
jal ra PrintNewline
mv s1 a0
addi sp sp -4
la s1 __str__12
sw s1 0(sp)
jal ra PrintString
mv s1 a0
addi sp sp 4
addi sp sp -4
addi s1 fp -64
lw s1 0(s1)
addi sp sp -4
sw s1 0(sp)
li s1 2
lw s2 0(sp)
addi sp sp 4
addi t0 x0 1
li t1 1
mul t1 s1 t0
add s2 s2 t1
mv s1 s2
sw s1 0(sp)
jal ra PrintInt
mv s1 a0
addi sp sp 4
jal ra PrintNewline
mv s1 a0
addi sp sp -4
la s1 __str__13
sw s1 0(sp)
jal ra PrintString
mv s1 a0
addi sp sp 4
addi sp sp -4
addi s1 fp -56
lw s1 0(s1)
addi sp sp -4
sw s1 0(sp)
li s1 1
lw s2 0(sp)
addi sp sp 4
li t0 4
li t1 1
mul t1 s1 t0
sub s2 s2 t1
mv s1 s2
sw s1 0(sp)
jal ra PrintInt
mv s1 a0
addi sp sp 4
addi sp sp -4
la s1 __str__14
sw s1 0(sp)
jal ra PrintString
mv s1 a0
addi sp sp 4
addi sp sp -4
addi s1 fp -56
lw s1 0(s1)
addi sp sp -4
sw s1 0(sp)
li s1 2
lw s2 0(sp)
addi sp sp 4
li t0 4
li t1 1
mul t1 s1 t0
sub s2 s2 t1
mv s1 s2
sw s1 0(sp)
jal ra PrintInt
mv s1 a0
addi sp sp 4
addi sp sp -4
la s1 __str__15
sw s1 0(sp)
jal ra PrintString
mv s1 a0
addi sp sp 4
addi sp sp -4
addi s1 fp -64
lw s1 0(s1)
addi sp sp -4
sw s1 0(sp)
li s1 1
lw s2 0(sp)
addi sp sp 4
li t0 1
li t1 1
mul t1 s1 t0
sub s2 s2 t1
mv s1 s2
sw s1 0(sp)
jal ra PrintInt
mv s1 a0
addi sp sp 4
addi sp sp -4
la s1 __str__16
sw s1 0(sp)
jal ra PrintString
mv s1 a0
addi sp sp 4
addi sp sp -4
addi s1 fp -64
lw s1 0(s1)
addi sp sp -4
sw s1 0(sp)
li s1 2
lw s2 0(sp)
addi sp sp 4
li t0 1
li t1 1
mul t1 s1 t0
sub s2 s2 t1
mv s1 s2
sw s1 0(sp)
jal ra PrintInt
mv s1 a0
addi sp sp 4
li s1 0
mv a0 s1
j _ptr
addi sp sp 16
_ptr:
addi sp fp -48
lw s11 44(sp)
lw s10 40(sp)
lw s9 36(sp)
lw s8 32(sp)
lw s7 28(sp)
lw s6 24(sp)
lw s5 20(sp)
lw s4 16(sp)
lw s3 12(sp)
lw s2 8(sp)
lw s1 4(sp)
lw ra 0(sp)
addi sp sp 48
lw fp 0(sp)
addi sp sp 4
jr ra
TwoPointers:
addi sp sp -4
sw fp 0(sp)
mv fp sp
addi sp sp -48
sw ra 0(sp)
sw s1 4(sp)
sw s2 8(sp)
sw s3 12(sp)
sw s4 16(sp)
sw s5 20(sp)
sw s6 24(sp)
sw s7 28(sp)
sw s8 32(sp)
sw s9 36(sp)
sw s10 40(sp)
sw s11 44(sp)
addi sp sp -16
li s1 12
sw s1 -52(fp)
addi s1 fp -52
sw s1 -56(fp)
li s1 12
sw s1 -60(fp)
addi s1 fp -60
sw s1 -64(fp)
addi sp sp -4
la s1 __str__17
sw s1 0(sp)
jal ra PrintString
mv s1 a0
addi sp sp 4
addi sp sp -4
addi s1 fp -56
lw s1 0(s1)
sw s1 0(sp)
jal ra PrintInt
mv s1 a0
addi sp sp 4
jal ra PrintNewline
mv s1 a0
addi sp sp -4
la s1 __str__18
sw s1 0(sp)
jal ra PrintString
mv s1 a0
addi sp sp 4
addi sp sp -4
addi s1 fp -64
lw s1 0(s1)
sw s1 0(sp)
jal ra PrintInt
mv s1 a0
addi sp sp 4
jal ra PrintNewline
mv s1 a0
jal ra PrintNewline
mv s1 a0
addi sp sp -4
la s1 __str__19
sw s1 0(sp)
jal ra PrintString
mv s1 a0
addi sp sp 4
addi sp sp -4
addi s1 fp -56
lw s1 0(s1)
addi sp sp -4
sw s1 0(sp)
addi s1 fp -64
lw s1 0(s1)
lw s2 0(sp)
addi sp sp 4
sub s1 s2 s1
srai s1 s1 2
sw s1 0(sp)
jal ra PrintInt
mv s1 a0
addi sp sp 4
jal ra PrintNewline
mv s1 a0
addi sp sp -4
la s1 __str__20
sw s1 0(sp)
jal ra PrintString
mv s1 a0
addi sp sp 4
addi sp sp -4
addi s1 fp -64
lw s1 0(s1)
addi sp sp -4
sw s1 0(sp)
addi s1 fp -56
lw s1 0(s1)
lw s2 0(sp)
addi sp sp 4
sub s1 s2 s1
srai s1 s1 2
sw s1 0(sp)
jal ra PrintInt
mv s1 a0
addi sp sp 4
jal ra PrintNewline
mv s1 a0
li s1 0
mv a0 s1
j _TwoPointers
addi sp sp 16
_TwoPointers:
addi sp fp -48
lw s11 44(sp)
lw s10 40(sp)
lw s9 36(sp)
lw s8 32(sp)
lw s7 28(sp)
lw s6 24(sp)
lw s5 20(sp)
lw s4 16(sp)
lw s3 12(sp)
lw s2 8(sp)
lw s1 4(sp)
lw ra 0(sp)
addi sp sp 48
lw fp 0(sp)
addi sp sp 4
jr ra
PrintString:
  addi sp sp -4
  sw ra 0(sp)
  lw a1 4(sp) 
  addi a0 x0 4
  ecall
  jal PrintNewline
  lw ra 0(sp)
  addi sp sp 4
  jr ra

PrintInt:
  addi sp sp -4
  sw ra 0(sp)
  lw a1 4(sp) 
  addi a0 x0 1
  ecall
  jal PrintNewline
  lw ra 0(sp)
  addi sp sp 4
  jr ra

PrintChar:
  addi sp sp -4
  sw ra 0(sp)
  lb a1 4(sp)
  andi a1 a1 0xff 
  addi a0 x0 11
  ecall
  jal PrintNewline
  lw ra 0(sp)
  addi sp sp 4
  jr ra

PrintBool:
  addi sp sp -4
  sw ra 0(sp)
  lw a1 4(sp) 
  addi a0 x0 1
  ecall
  jal PrintNewline
  lw ra 0(sp)
  addi sp sp 4
  jr ra

PrintNewline:
  addi a1 x0 10 #Load newline char
  addi a0 x0 11
  ecall
  mv a0 x0
  jr ra

PrintInts:
  addi sp sp -8
  sw ra 4(sp)
  lw t0 8(sp)
  sw t0 0(sp)
  jal PrintInt
  lw t0 12(sp)
  sw t0 0(sp)
  jal PrintInt
  lw t0 16(sp)
  sw t0 0(sp)
  jal PrintInt
  lw ra 4(sp)
  addi sp sp 8
  jr ra

PrintChars:
  addi sp sp -8
  sw ra 4(sp)
  lb t0 8(sp)
  sb t0 0(sp)
  jal PrintChar
  lb t0 9(sp)
  sb t0 0(sp)
  jal PrintChar
  lb t0 10(sp)
  sb t0 0(sp)
  jal PrintChar
  lw ra 4(sp)
  addi sp sp 8
  jr ra
  

PrintMixed:
  addi sp sp -8
  sw ra 4(sp)
  lb t0 8(sp)
  sb t0 0(sp)
  jal PrintChar
  lb t0 9(sp)
  sb t0 0(sp)
  jal PrintChar
  lw t0 12(sp)
  sw t0 0(sp)
  jal PrintInt
  lw t0 16(sp)
  sw t0 0(sp)
  jal PrintInt
  lb t0 20(sp)
  sb t0 0(sp)
  jal PrintChar
  lw t0 24(sp)
  sw t0 0(sp)
  jal PrintInt
  lw ra 4(sp)
  addi sp sp 8
  jr ra
  
